[package]
name = "sdl_example"
version = "0.1.0"
authors = ["vengeq <vengeq@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.32.2"
rand = "0.7"
libc = "0.2.59"
sdl2-sys = "0.32.6"
log4rs = "0.8.3"
log = "0.4.7"

[features]
default = ["sdl2/ttf"]

[profile.release]
lto = true