[package]
name = "sdl_example"
version = "0.1.0"
authors = ["vengeq <vengeq@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.32.2"
rand = "0.7"
libc = "0.2.59"
sdl2-sys = "0.32.6"
gfx_window_sdl = "0.9.1"
gfx = "0.18"