refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  application:
    kind: file
    path: "log/logger.log"
    encoder:
      pattern: "{l:<5.6}:{d(%Y-%m-%d %H:%M:%S %Z)(utc)} - {m}{n}"
root:
  level: warn
  appenders:
    - stdout
loggers:
  sdl_example:
    level: info
    appenders:
      - application
    additive: true