refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  appli:
    kind: file
    path: "log/logger.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  app:
    level: info
    appenders:
      - appli
    additive: false